### ISSUE TITLE
Update Conference date and Venue in the banner of Welcome page

### ISSUE THREAD

**Issue by sucitw** [sciwork/swconf#27]
The following information was confirmed: 
The conference will be held from 12/9 to 12/10 at the [MIRC](https://eic2.web.nycu.edu.tw/) of National Yang Ming Chiao Tung University.

Please help to update the date and venue in the banner of Welcome page

<img width="524" alt="image" src="https://github.com/sciwork/swconf/assets/6697164/87ee2895-610f-46b5-bc42-b48474081385">
.

**Comment by chestercheng** [comment]
I have updated in #28
